# Generated by Django 4.2.4 on 2023-10-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0002_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedhomework",
            name="submit_date",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
