# Generated by Django 4.2.4 on 2023-10-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0005_notes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
