# Generated by Django 4.2.4 on 2023-10-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_modelcategory_physicsmodels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelcategory",
            name="title",
        ),
        migrations.AddField(
            model_name="modelcategory",
            name="description",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
